---
configure_explorer: true
configure_hostname: false
custom_hostname: windows-ansible
configure_start_menu: true
configure_taskbar: true
disable_mouse_acceleration: true
remote_desktop_enabled: true
remove_desktop_icons: false
set_sound_scheme: true

install_windows_updates: true
windows_updates_reboot: true
update_categories:
  # You can install only specific updates by uncommenting it
  # * - installs all updates
  - "*"
  # - Critical Updates
  # - Definition Updates
  # - Developer Kits
  # - Feature Packs
  # - Security Updates
  # - Service Packs
  # - Tools
  # - Update Rollups
  # - Updates
  # - Upgrades

change_power_plan: true
# high_performance
# balanced
# power_saver
power_plan: "high_performance"

install_chocolatey_packages: true
choco_installed_packages:
  - Firefox
  - git
  - git-lfs
  - microsoft-windows-terminal
  - powershell-core
  - python3
  - sharex
  - vlc
  - vscode
  - sysinternals
  - irfanview
  - emclient
  - pandoc
  - foxitreader
  - 7zip
  - GoogleChrome
  - SpeedCrunch
  - obsidian
  - powerchute-personal
  - speedcrunch
  - discord
  - slack
  - zadig
  - winmerge
  - sublimetext4
  - sublimimerge
  - putty
  - pycharm-community
  - openjdk11
  - jre8
  - hxd
  - gping
  - github-desktop
  - ftdi-drivers
  - ftprog
  - edrawings-viewer
  - dotnetfx
  - dfu-util
  - dotnet-5.0-runtime
  - dotnet-6.0-runtime
  - dotnet-7.0-runtime
  - vcredist2015
  - vcredist140
  - arduino-cli
  - docker-desktop
  - everything
  - MiKTeX
  - realterm
  - chocolateygui


install_winget_packages: true
winget_packages:
  - name: MullvadVPN.MullvadVPN
    source: winget 
  - name: AgileBits.1Password
    source: winget 
  - name: Microsoft.RemoteDesktopClient
    source: winget 
  - name: UbiquitiInc.UI
    source: winget 
  - name: Adobe.Acrobat.Reader.64-bit
    source: winget 
  - name: Nvidia.Broadcast
    source: winget 
  - name: Nvidia.GeForceExperience
    source: winget 
  - name: dorssel.usbipd-win
    source: winget 
  - name: Olivia.VIA
    source: winget 
  - name: Chocolatey.ChocolateyGUI
    source: winget
  - name: Microsoft.PowerToys
    source: winget

install_fonts: true
installed_nerdfonts:
  - FiraCode
  - FantasqueSansMono
  - Terminus
  - CascadiaCode
  - DejaVuSansMono

install_ohmyposh: true

# List of features: "Get-WindowsOptionalFeature -Online"
install_windows_features: false
windows_features:
  Microsoft-Hyper-V: true
  Printing-PrintToPDFServices-Features: true
  NetFx3: true
  WCF-Services45: true
  WCF-TCP-PortSharing45: true
  MediaPlayback: true
  WindowsMediaPlayer: true
  SmbDirect: true
  MicrosoftWindowsPowerShellV2Root: true
  MicrosoftWindowsPowerShellV2: true
  WorkFolders-Client: true
  MSRDC-Infrastructure: true
  TelnetClient: true
  NetFx4-AdvSrvs: true
  Printing-Foundation-Features: true
  Printing-Foundation-InternetPrinting-Client: true
  SearchEngine-Client-Package: true
  ServicesForNFS-ClientOnly: true
  HypervisorPlatform: true
  VirtualMachinePlatform: true
  Microsoft-Windows-Subsystem-Linux: true
  Microsoft-Hyper-V-All: true
  Microsoft-Hyper-V: true
  Microsoft-Hyper-V-Tools-All: true
  Microsoft-Hyper-V-Management-PowerShell: true
  Microsoft-Hyper-V-Hypervisor: true
  Microsoft-Hyper-V-Services: true
  Microsoft-Hyper-V-Management-Clients: true
  Containers: true
  Containers-HNS: true
  Containers-SDN: true

# List of valid distributions that can be installed:
# wsl-alpine
# wsl-archlinux
# wsl-debiangnulinux
# wsl-fedoraremix
# wsl-kalilinux
# wsl-opensuse
# wsl-sles
# wsl-ubuntu-1604
# wsl-ubuntu-1804
# wsl-ubuntu-2004
install_wsl2: true
wsl2_distribution: wsl-ubuntu-2204

remove_bloatware: true
bloatware:
  - Microsoft.BingNews
  - Microsoft.BingWeather
  - Microsoft.GamingApp
  - Microsoft.GetHelp
  - Microsoft.Getstarted
  - GamingServices
  # - Microsoft.Messaging
  - Microsoft.Microsoft3DViewer
  - Microsoft.MicrosoftOfficeHub
  - Microsoft.MicrosoftSolitaireCollection
  - Microsoft.MicrosoftStickyNotes
  - Microsoft.MixedReality.Portal
  # - Microsoft.MSPaint
  - Microsoft.Office.OneNote
  - Microsoft.OneConnect
  - Microsoft.People
  - Microsoft.PowerAutomateDesktop
  - Microsoft.Print3D
  - Microsoft.ScreenSketch
  - Microsoft.SkypeApp
  - Microsoft.MicrosoftStickyNotes
  - Microsoft.Todos
  # - Microsoft.Windows.Photos
  - Microsoft.WindowsAlarms
  # - Microsoft.WindowsCalculator
  - Microsoft.Wallet
  - Microsoft.WindowsCamera
  # - microsoft.windowscommunicationsapps
  - Microsoft.WindowsFeedbackHub
  - Microsoft.WindowsMaps
  - Microsoft.WindowsSoundRecorder
  - Microsoft.Xbox
  - Microsoft.Xbox.TCUI
  - Microsoft.XboxApp
  - Microsoft.XboxGameOverlay
  - Microsoft.XboxSpeechToTextOverlay
  - Microsoft.XboxIdentityProvider
  # - Microsoft.YourPhone
  - Microsoft.ZuneMusic
  - Microsoft.ZuneVideo
  - MicrosoftTeams
  - Microsoft.3DBuilder


configure_storage_sense: true
storage_sense:
  enabled: true
  run_frequency: 1
  delete_unused_files: true
  delete_recycle_bin_files: true
  recycle_bin_age: 14
  delete_downloads_files: true
  downloads_age: 14

defrag_volumes: true
include_volumes:
  - C
